vich_uploader:
    db_driver: orm

    mappings:
        articles:
            uri_prefix: /images/photos-articles
            upload_destination: '%kernel.project_dir%/public/images/photos-articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
